app:
  max-active-users: 5 # 예매 페이지에 동시 진입 가능한 최대 사용자 수
  access-key-ttl-minutes: 1 # 예매 페이지 접근 키의 유효시간 (단위: 분)

spring:
  application:
    name: ticketmon-go
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # .env 값 우선 사용, 없으면 dev 기본값
    # 🚨 기본값은 'prod'입니다. 로컬 개발 시에만 'dev'로 바꿔주세요.

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration  # 임시로 DB 자동 설정 제외 (설정이 없을 경우 에러 방지)
    # 실제 DB 사용 시엔 위 라인 제거. 현재는 데이터소스 수동 설정을 의미

  jackson:
    time-zone: Asia/Seoul  # [기본 설정] 한국 사용자 대상이므로 KST 기준으로 기본 직렬화 설정함
    # 추후 글로벌 확장 시 UTC 또는 타임존 동적 처리로 대체 가능

server:
  port: ${SERVER_PORT:8080}  # .env에서 설정한 포트 사용, 기본은 8080

logging:
  level:
    root: ${LOG_LEVEL:INFO}  # 로그 레벨 설정 (INFO / WARN / ERROR)