spring:
  application:
    name: ticketmon-go
  profiles:
    active: dev  # 개발 중에는 dev, 배포 시 prod로 교체

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  jackson:
    time-zone: Asia/Seoul  # [기본 설정] 한국 사용자 대상이므로 KST 기준으로 기본 직렬화 설정함
    # 추후 글로벌 확장 시 UTC 또는 타임존 동적 처리로 대체 가능