name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Backend to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and Deploy Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "✅ EC2 접속 완료. 기존 컨테이너 중지 중..."
            docker stop ticketmon-backend || true
            docker rm ticketmon-backend || true

            echo "⬇️ 최신 이미지 Pull 중..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/backend

            echo "🚀 새 컨테이너 실행 중..."
            docker run -d \
              --name ticketmon-backend \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -v /home/ec2-user/app/application-prod.yml:/app/config/application-prod.yml \
              ${{ secrets.DOCKER_USERNAME }}/backend

            echo "🎉 배포 완료!"
